name: AUR

on:
  workflow_dispatch:
  push:
    branches: [aur]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.3']
        cabal: [latest]
        os: [ubuntu-latest]
    name: Haskell GHC ${{ matrix.ghc }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      - name: Build
        run: |
          export PATH=~/.cabal/bin:$PATH
          cabal build all
          cabal install --install-method=copy --overwrite-policy=always --enable-executable-stripping
          mailctl --version
          VERSION=$(grep '^version:' mailctl.cabal | awk '{print $2}')
          EXE_NAME=mailctl-$VERSION-${{ runner.os }}
          cp ~/.cabal/bin/mailctl $EXE_NAME
          sha256sum $EXE_NAME > $EXE_NAME.sha256
          sed -e "s/^pkgver=.*$/pkgver=$VERSION/" aur/PKGBUILD >PKGBUILD
          ls -l

      - name: Release AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: mailctl-bin
          pkgbuild: ./aur/PKGBUILD
          assets: |
            ./aur/.INSTALL
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.ref }}

